anwesende/room/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

import anwesende.room.views as arv

app_name = "room"
urlpatterns = [
    path("",
         view=arv.HomeView.as_view(), name="home"),
    path("faq",
         view=arv.FAQView.as_view(), name="faq"),
    path("import",
         view=arv.ImportView.as_view(), name="import"),
    path("qrcodes/<pk>",
         view=arv.QRcodesByImportView.as_view(), name="qrcodes-byimport"),
    path("qrcodes/<organization>/<department>/<building>",
         view=arv.QRcodesByRoomsView.as_view(), name="qrcodes-byorgdepbld"),
    path("qrcodes/<organization>/<department>/<building>/<room>",
         view=arv.QRcodesByRoomsView.as_view(), name="qrcodes-byorgdepbldrm"),
    path("qrcode/<hash>",
         view=arv.QRcodeView.as_view(), name="qrcode"),
    path("S<hash>",
         view=arv.VisitView.as_view(), name="visit"),
    path("search",
         view=arv.SearchView.as_view(), name="search"),
    path("search_room",
         view=arv.SearchByRoomView.as_view(), name="searchroom"),
    path("show_rooms",
         view=arv.ShowRoomsView.as_view(), name="show-rooms"),
    path("show_rooms/<organization>/<department>",
         view=arv.ShowRoomsView.as_view(), name="show-rooms-department"),
    path("show_rooms/<organization>/<department>/<building>",
         view=arv.ShowRoomsView.as_view(), name="show-rooms-building"),
    path("report_dept",
         view=arv.VisitsByDepartmentView.as_view(), name="report_dept"),
    path("report_week",
         view=arv.VisitorsByWeekView.as_view(), name="report_week"),
    path("thankyou/S<hash>",
         view=arv.ThankyouView.as_view(), name="thankyou"),
    path("thankyou/S<hash>/seats",
         view=arv.ThankyouView.as_view(with_seats=True), name="thankyouseats"),
    path("thankyou/visitors_presentN=<visitors_presentN>",
         view=arv.LegacyThankyouView.as_view(), name="legacy_thankyou"),
    path("uncookie",
         view=arv.UncookieView.as_view(), name="uncookie"),
    path('favicon.ico', RedirectView.as_view(
        url=staticfiles_storage.url('images/favicon.ico')))
]

anwesende/users/urls.py
from django.urls import path

import anwesende.users.views as auv

app_name = "users"
urlpatterns = [
    path("~redirect/", view=auv.user_redirect_view, name="redirect"),
    path("~update/", view=auv.user_update_view, name="update"),
    path("<str:username>/", view=auv.user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("anwesende.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("anwesende.room.urls", namespace="room")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

anwesende/users/models.py
import django.contrib.auth.models as djcam
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(djcam.AbstractUser):
    """Default user for anwesende."""
    STAFF_GROUP = "datenverwalter"
    #: First and last name do not cover name patterns around the globe:
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def assign_datenverwalter_group(self) -> None:
        group = self.get_datenverwalter_group()
        self.groups.add(group)

    def is_datenverwalter(self) -> bool:
        return self.groups.filter(id=self.get_datenverwalter_group().id).exists()

    @classmethod
    def get_datenverwalter_group(cls) -> djcam.Group:
        if not djcam.Group.objects.filter(name=cls.STAFF_GROUP).exists():
            fresh_group = djcam.Group.objects.create(name=cls.STAFF_GROUP)  # noqa
        return djcam.Group.objects.get_by_natural_key(cls.STAFF_GROUP)

anwesende/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

anwesende/room/views.py
import datetime as dt
import json
import logging
import os
import traceback
import typing as tg

import django.contrib.auth.mixins as djcam
import django.contrib.auth.views as djcav
import django.contrib.messages as djcm
import django.db.models as djdm
from django.db.models import Count
import django.http as djh
import django.urls as dju
import django.utils.timezone as djut
import django.views.generic.base as djvgb
import vanilla as vv  # Django vanilla views
from django.conf import settings

import anwesende.room.excel as are
import anwesende.room.forms as arf
import anwesende.room.models as arm
import anwesende.room.reports as arr
import anwesende.room.utils as aru
import anwesende.utils.date as aud
import anwesende.utils.lookup  # noqa,  registers lookup
import anwesende.utils.qrcode as auq

COOKIENAME = 'anwesende'


class AddIsDatenverwalter:
    """
    Sets user and is_datenverwalter flag in self and in context.
    """
    def dispatch(self, request: djh.HttpRequest, *args, **kwargs) -> djh.HttpResponse:
        self.user = self.request.user  # type: ignore
        self.is_datenverwalter = self.user.is_authenticated \
            and self.user.is_datenverwalter()
        return super().dispatch(request, *args, **kwargs)  # type: ignore

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # type: ignore
        context['user'] = self.user
        context['is_datenverwalter'] = self.is_datenverwalter
        return context


class AddSettings:
    """Put 'settings' in context: base.html requires it."""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # type: ignore
        context['settings'] = settings
        return context


class FAQView(AddSettings, vv.TemplateView):
    template_name = "room/faq.html"


class HomeView(AddSettings, vv.TemplateView):
    template_name = "room/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dummyseat'] = arm.Seat.get_dummy_seat()
        return context


class ImportView(AddIsDatenverwalter, AddSettings, vv.FormView):
    """Import-Excel-for-QR-code-creation dialog."""
    form_class = arf.UploadFileForm
    template_name = "room/import.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.is_datenverwalter:
            interval = dt.timedelta(days=8)
            imports = arm.Importstep.displayable_importsteps(interval)
        else:
            room = arm.Seat.get_dummy_seat().room
            importstep = room.importstep
            importstep.organization = room.organization  # type: ignore[attr-defined]
            importstep.department = room.department  # type: ignore[attr-defined]
            imports = [importstep] 
        context['imports'] = imports
        context['settings'] = settings
        return context

    def form_invalid(self, form: arf.UploadFileForm):
        logging.getLogger('error').error(f"ImportView invalid: {form.errors}")
        return super().form_invalid(form)

    def form_valid(self, form: arf.UploadFileForm):
        filename = form.cleaned_data['excelfile']  # form has created the file
        self.importstep = are.create_seats_from_excel(filename, self.user)
        os.remove(filename)
        logging.info(f"ImportView({self.importstep})")
        return super().form_valid(form)

    def get_success_url(self):
        return dju.reverse('room:qrcodes-byimport', kwargs=dict(pk=self.importstep.pk))

    def post(self, request, *args, **kwargs):
        if not self.is_datenverwalter:
            next = self.request.get_full_path()
            login_url = dju.reverse('account_login')
            return djcav.redirect_to_login(next, login_url, 'next')
        return super().post(request, *args, **kwargs)

class QRcodesByImportView(AddIsDatenverwalter, AddSettings, vv.DetailView):
    """Show printable QR codes created in one Importstep."""
    model = arm.Importstep
    template_name = "room/qrcodes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        seats = arm.Seat.objects.filter(room__importstep=self.object)
        context['seats'] = seats
        context['listtype'] = 'importstep'
        return context

    def get_object(self):
        object = super().get_object()
        if self.is_datenverwalter or object == arm.Seat.get_dummy_seat().room.importstep:
            return object
        else:
            raise djh.Http404


class QRcodesByRoomsView(djcam.LoginRequiredMixin, 
                         AddIsDatenverwalter, AddSettings, vv.TemplateView):
    """Show printable QR codes for one room or one building."""
    template_name = "room/qrcodes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seats'] = self.get_queryset().all()
        context['listtype'] = 'byrooms'
        return context

    def get(self, request, *args, **kwargs):
        pop_org_dept_bldg_room(self)
        return super().get(request, *args, **kwargs)
        
    def get_queryset(self):
        qs = arm.Seat.objects.filter(
                room__organization=self.organization,
                room__department=self.department,
                room__building=self.building)
        if self.room:
            return qs.filter(room__room=self.room)
        else:
            return qs

def pop_org_dept_bldg_room(view):
    """
    Get certain URL params (if present) which come in slash-escaped in original form.
    See aru.escape_slash for rationale.
    """
    for arg in ('organization', 'department', 'building', 'room'):
        val = view.kwargs.pop(arg, "")
        setattr(view, f"{arg}", aru.unescape_slash(val))  # the real value


class QRcodeView(AddIsDatenverwalter, AddSettings, vv.View):
    """Render one QR code as SVG."""
    def get(self, request, *args, **kwargs):
        if not self.is_datenverwalter \
                and kwargs['hash'] != arm.Seat.get_dummy_seat().hash:
            raise djh.Http404
        path = dju.reverse('room:visit', kwargs=dict(hash=kwargs['hash']))
        url = settings.SHORTURL_PREFIX + path
        qrcode_bytes = auq.qrcode_data(url, imgtype='svg')
        return djh.HttpResponse(qrcode_bytes, content_type="image/svg+xml")


class ShowRoomsView(djcam.LoginRequiredMixin,
                    AddIsDatenverwalter, AddSettings, vv.TemplateView):
    """Browse list of departments, buildings, rooms; navigate to QR codes."""
    template_name = "room/show_rooms.html"

    def get(self, request, *args, **kwargs):
        pop_org_dept_bldg_room(self)
        return super().get(request, *args, **kwargs)

    def get_context_data(self):
        context = super().get_context_data()
        if self.building:
            context['type'] = "building"
            context['rooms'] = arm.Room.objects.filter(
                    organization=self.organization,
                    department=self.department,
                    building=self.building)
        elif self.department:
            context['type'] = "department"
            context['buildings'] = (arm.Room.objects
                    .filter(organization=self.organization, 
                            department=self.department)
                    .order_by('building')
                    .values('building')
                    .annotate(rooms=Count("id", distinct=True)))
        else:
            context['type'] = "overview"
            context['departments'] = (arm.Room.objects
                    .order_by('organization', 'department')
                    .values('organization', 'department')
                    .annotate(buildings=Count("building", distinct=True)))
        return context


class VisitView(AddSettings, vv.CreateView):
    """Centerpiece: The registration dialog for room visitors."""
    model = arm.Visit
    form_class = arf.VisitForm
    template_name = "room/visit.html"

    def get_success_url(self):
        return dju.reverse('room:thankyou', 
                           kwargs=dict(hash=self.object.seat.hash))
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        hashvalue = self.kwargs['hash']
        if not arm.Seat.exists(hashvalue):
            raise djh.Http404()
        seat = arm.Seat.by_hash(hashvalue)
        ctx['seat'] = seat
        ctx['room'] = seat.room
        ctx['settings'] = settings
        retention_3g = settings.DATA_RETENTION_DAYS_STATUS_3G
        if settings.USE_STATUS_3G_FIELD and \
           retention_3g <= settings.DATA_RETENTION_DAYS:
            ctx['status_3g_stmt_de'] = ("Der 3G-Status wird bereits nach %d Tagen gelöscht." %
                                       retention_3g)
            ctx['status_3g_stmt_en'] = ("The vaccination status will be deleted after %d days." %
                                       retention_3g)
        else:
            ctx['status_3g_stmt_de'] = ctx['status_3g_stmt_en'] = ""
        return ctx

    
    def get_form(self, data=None, files=None, **kwargs):
        if data:  # POST
            data = {k: v for k, v in data.items()}  # extract ordinary dict
            return arf.VisitForm(data=data, files=files, **kwargs)
        # else GET:
        if COOKIENAME in self.request.COOKIES:
            try:
                thecookie = self.request.COOKIES[COOKIENAME]
                initial = json.loads(thecookie)
            except json.JSONDecodeError as err:
                tb = traceback.format_exc(limit=12, chain=True)
                logging.warning(f"VisitView: broken cookie >>>>{thecookie}<<<<\n{tb}")
                initial = dict(cookie=arm.Visit.make_cookie())
                logging.info(f"VisitView: ersatz {initial}")
        else:
            initial = dict(cookie=arm.Visit.make_cookie())
            logging.info(f"VisitView: new {initial}")

anwesende/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

anwesende/templates/room/home.html
{% extends "base.html" %}

{% block content %}
  <h1>a.nwesen.de</h1>

  {% if request.user.is_authenticated %}
    <ul>
      <li>
        <a href="{% url 'room:import' %}">QR-Codes erzeugen</a>
      </li>
      <li>
        <a href="{% url 'room:show-rooms' %}">Räume und QR-Codes ansehen</a>
      </li>
      <li>
        <a href="{% url 'room:report_dept' %}">Bericht: Besuche gesamt nach Department</a>
      </li>
      <li>
        <a href="{% url 'room:report_week' %}">Bericht: Besucher nach Woche</a>
      </li>
      <li>
        <a href="{% url 'room:search' %}">Nach Personen suchen</a>
      </li>
    </ul>
  {% endif %}

  <p>
    <span class="languagemark">DE</span>: 
    Eine Open-Source-Webanwendung zur Anwesenheitserfassung.
    Dient im Infektionsfall zur Kontaktverfolgung in Zeiten der Pandemie:
    <ol>
      <li>
        Teilnehmende Hochschulen 
        <a href="{% url 'room:import' %}">registrieren ihre Räume</a><sup>*</sup>, 
        erhalten für jeden
        Sitzplatz einen QR-Code 
        (<a href="{% url 'room:qrcodes-byimport' dummyseat.room.importstep.pk %}">Beispiel</a><sup>*</sup>)
        und kleben diesen auf.
      </li>
      <li>
        Besucher von Räumen scannen ihren QR-Code
        (<a href="{% url 'room:qrcode' dummyseat.hash %}">Beispiel</a><sup>*</sup>), 
        füllen ein Formular mit Kontaktdaten aus 
        (<a href="{% url 'room:visit' dummyseat.hash %}">Beispiel</a><sup>*</sup>)
        und geben dabei die Anwesenheitszeit an.
        <br>
        Diese Daten werden zentral gespeichert, geordnet
        nach Räumen und Zeiten.
      </li>
      <li>
        Im Infektionsfall meldet sich der/die Infizierte bei der Hochschule.
        <br>
        Die Hochschule ruft für die fraglichen Tage die Daten dieser Person ab
        (über <a href="{% url 'room:search' %}">dieses Formular</a><sup>*</sup>)
        und erhält für jeden besuchten Raum die ganze Kontaktgruppe von 
        Personen, die überlappend im gleichen Raum gewesen sind.
      </li>
      <li>
        Die Hochschule gibt diese Daten gemäß ihrer gesetzlichen Verpflichtung
        an das Gesundheitsamt weiter.
      </li>
    </ol>
    <p>
      <sup>*</sup>Diese Beispiellinks gehören zu einem Demonstrationsmodus.
      Sie erzwingen an Stellen, die normalerweise nur
      für die Datenverwalter_innen zugänglich sind, einen Fantasiesitzplatz
      in der Fantasieorganisation '{{ settings.DUMMY_ORG }}'. <br>
      Die Daten, die man so ins Anwesenheitsformular eingibt, 
      sind öffentlich sichtbar und lassen sich über das zugehörige
      Suchformular auch öffentlich abrufen. <br>
      Das wirkliche Anwesenheitsformular erreicht man über das Scannen
      eines QR-Codes, der an einem echten Sitzplatz aufgeklebt ist. <br>
      Das wirkliche Suchformular erreichen nur Datenverwalter_innen mit Passwort.
    </p>
  </p>
  <p>
    <span class="languagemark">EN</span>: 
    An open source web application for people to register their presence.
    Meant to help tracing contacts when someone got infected in pandemic times.
    This contact tracing is required by law.
  </p>
  <p>
    To use it as a visitor, scan the QR code posted at your seat and fill
    in the form shown. Details are explained there.
  </p>
  
{% endblock content %}

anwesende/templates/room/qrcodes.html
{% extends "base.html" %}

{% block content %}
  {% if listtype == "importstep" %}
    <p>{{ settings.SHORTURL_PREFIX }}{% url 'room:qrcodes-byimport' object.pk %}</p>
    <p>
      Dieser Importschritt hat
      {{ object.num_new_rooms }} 
      {{ object.num_new_rooms|pluralize:"neuen Raum,neue Räume" }} und
      {{ object.num_new_seats }}
      {{ object.num_new_seats|pluralize:"neuen Sitzplatz,neue Sitzplätze" }}
      erzeugt.
      {% if object.num_existing_seats %}
        In der Liste der QR-Codes unten finden sich außerdem
        {{ object.num_existing_rooms }} schon vorher 
        vorhanden{{ object.num_existing_rooms|pluralize:"er Raum,e Räume" }}
        und 
        {{ object.num_existing_seats }} schon vorher
        vorhanden{{ object.num_existing_seats|pluralize:"er Sitzplatz,e Sitzplätze" }}.
      {% endif %}
    </p>
  {% elif listtype == "byrooms" %}
    <code>organization</code>: {{ view.organization }}; 
    <code>department</code>: {{ view.department }};
    <code>building</code>: {{ view.building }};
    <code>room</code>: {{ view.room }};
    <code>row_dist</code>: {{ seats.0.room.row_dist }};
    <code>seat_dist</code>: {{ seats.0.room.seat_dist }};
  {% endif %}
  <hr>
    {% for seat in seats %}
      <div class="row align-items-center">
        <div>
          <img class="qrcode" src="{% url 'room:qrcode' seat.hash %}" alt="QR Code" aria-roledescription="QR Code">
        </div>
        <div style="padding-left: 1pc;" aria-roledescription="QR Code Information">
          <span class="qrb-item">Please scan QR code and register your presence.</span>
          <br>
          <span class="qrb-item">{{ settings.SHORTURL_PREFIX }}{% url 'room:visit' seat.hash %}</span>
          <br>
          <span class="qrb-label">date: </span>
          <span class="qrb-item">{{seat.room.importstep.when | date:"Y-m-d"}}</span>
          <br>
          <span class="qrb-label">organization: </span>
          <span class="qrb-item">{{seat.room.organization}}</span>
          <br>
          <span class="qrb-label">department: </span>
          <span class="qrb-item">{{seat.room.department}}</span>
          <br>
          <span class="qrb-label">building: </span>
          <span class="qrb-item">{{seat.room.building}}</span>
          <br>
          <span class="qrb-label">room: </span>
          <span class="qrb-markeditem">{{seat.room.room}}</span>
          <br>
          <span class="qrb-label"> </span>
          <span class="qrb-largeitem">{{seat.seatname}}</span>
        </div>
      </div>
    {% endfor %}
{% endblock content %}

anwesende/templates/room/search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Suche nach Besuchen von Personen</h1>
  <ol>
    <li>
      Beschreiben Sie die gewünschte Person mit dem Formular unten und
      geben Sie einen passenden Zeitraum an.
      Alle Kriterien müssen zugleich erfüllt sein, damit sie zutreffen.
    </li>
    <li>
      Prüfen Sie das Suchergebnis. Zu viele Treffer?
      Dann schärfere Kriterien benutzen.
      Am besten eignet sich normalerweise die Emailadresse.
    </li>
    <li>
      Wenn die Trefferliste passend aussieht, mit Knopf Nummer 2
      die Liste der Kontakte ansehen und auf Plausibilität prüfen. <br>
      Wenn die auch in Ordnung ist, mit Knopf 3 die Liste als Excel herunterladen.
    </li>
  </ol>
  <p>
    Im Formular unten steht das Prozentzeichen % für Teile, die
    egal oder unbekannt sind.
  </p>
  {% crispy form %}
  
  {% if display_switch == 'invalid' %}
    <!-- form is invalid, no results to be shown -->
  {% elif display_switch == 'too_many_results' %}
      <h2>{{ NUMRESULTS }} results</h2>
      <p>
        Will show at most {{ LIMIT }} results. 
        Please use more specific search criteria.
      </p>
  {% elif display_switch == 'submit_visit' or display_switch == 'submit_visitgroup' %}
    {% include "room/_searchhits.html" %}
  {% else %}
    <p>Something is wrong! (display_switch {{ display_switch }})</p>
  {% endif %}
  
  <p>
    <a id=searchroom-link" href="{% url 'room:searchroom' %}"
    >Suche per Raum (statt per Person)</a>
  </p>
{% endblock content %}

anwesende/templates/room/show_rooms.html
{% extends "base.html" %}
{% load anwesende_tags %}

{% block content %}
  <h1>QR-Codes für vorhandene Räume</h1>

  {% if type == "overview" %}
    
    <h2>Hochschuleinheiten (departments)</h2>
    
    <table class="table table-sm table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Organization</th>
          <th scope="col">Department</th>
          <th scope="col">#Buildings</th>
        </tr>
      </thead>
      <tbody>
      {% for dpt in departments %}
        <tr>
          <td>{{ dpt.organization }}</td>
          <td>{{ dpt.department }}</td>
          <td><a href="{% url 'room:show-rooms-department' organization=dpt.organization|escape_slash department=dpt.department|escape_slash %}"
                 class="show-rooms-department"
              >{{ dpt.buildings }} Gebäude</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <p><a href="/">Zurück</a></p>

  {% elif type == "department" %}

    <h2>Gebäude von {{ view.department }}</h2>
    
    <table class="table table-sm table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Building</th>
          <th scope="col">#Rooms</th>
          <th scope="col">QR codes</th>
        </tr>
      </thead>
      <tbody>
      {% for bldg in buildings %}
        <tr>
          <td>{{ bldg.building }}</td>
          <td><a href="{% url 'room:show-rooms-building' organization=view.organization|escape_slash department=view.department|escape_slash building=bldg.building|escape_slash %}"
                 class="show-rooms-building"
              >{{ bldg.rooms }} Räume</a></td>
          <td><a href="{% url 'room:qrcodes-byorgdepbld' organization=view.organization|escape_slash department=view.department|escape_slash building=bldg.building|escape_slash %}"
                 class="qrcodes-building"
              >((alle))</a></td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <p><a href="{% url 'room:show-rooms' %}">Zurück</a></p>
    
  {% elif type == "building" %}

    <h2>Räume von Gebäude {{ view.building }}</h2>
    
    <table class="table table-sm table-hover">
      <thead class="thead-light">
        <tr>
          <th scope="col">Room</th>
          <th scope="col">row_dist</th>
          <th scope="col">seat_dist</th>
          <th scope="col">seat_last</th>
        </tr>
      </thead>
      <tbody>
      {% for room in rooms %}
        <tr>
          <td><a href="{% url 'room:qrcodes-byorgdepbldrm' organization=view.organization|escape_slash department=view.department|escape_slash building=view.building|escape_slash room=room.room|escape_slash %}"
                 class="qrcodes-room"
              >{{ room.room }}</a></td>
          <td>{{ room.row_dist }}</td>
          <td>{{ room.seat_dist }}</td>
          <td>{{ room.seat_last }}</td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
    <p><a href="{% url 'room:show-rooms-department' organization=view.organization|escape_slash department=view.department|escape_slash %}">Zurück</a></p>
    
  {% else %}
    
    <p><code>type = "{{ type }}"</code>. Wie, bitte?</p>
  
  {% endif %}

{% endblock content %}