anwesende/room/urls.py
from django.contrib.staticfiles.storage import staticfiles_storage
from django.urls import path
from django.views.generic.base import RedirectView

import anwesende.room.views as arv

app_name = "room"
urlpatterns = [
    path("",
         view=arv.HomeView.as_view(), name="home"),
    path("faq",
         view=arv.FAQView.as_view(), name="faq"),
    path("import",
         view=arv.ImportView.as_view(), name="import"),
    path("qrcodes/<pk>",
         view=arv.QRcodesByImportView.as_view(), name="qrcodes-byimport"),
    path("qrcodes/<organization>/<department>/<building>",
         view=arv.QRcodesByRoomsView.as_view(), name="qrcodes-byorgdepbld"),
    path("qrcodes/<organization>/<department>/<building>/<room>",
         view=arv.QRcodesByRoomsView.as_view(), name="qrcodes-byorgdepbldrm"),
    path("qrcode/<hash>",
         view=arv.QRcodeView.as_view(), name="qrcode"),
    path("S<hash>",
         view=arv.VisitView.as_view(), name="visit"),
    path("search",
         view=arv.SearchView.as_view(), name="search"),
    path("search_room",
         view=arv.SearchByRoomView.as_view(), name="searchroom"),
    path("show_rooms",
         view=arv.ShowRoomsView.as_view(), name="show-rooms"),
    path("show_rooms/<organization>/<department>",
         view=arv.ShowRoomsView.as_view(), name="show-rooms-department"),
    path("show_rooms/<organization>/<department>/<building>",
         view=arv.ShowRoomsView.as_view(), name="show-rooms-building"),
    path("report_dept",
         view=arv.VisitsByDepartmentView.as_view(), name="report_dept"),
    path("report_week",
         view=arv.VisitorsByWeekView.as_view(), name="report_week"),
    path("thankyou/S<hash>",
         view=arv.ThankyouView.as_view(), name="thankyou"),
    path("thankyou/S<hash>/seats",
         view=arv.ThankyouView.as_view(with_seats=True), name="thankyouseats"),
    path("thankyou/visitors_presentN=<visitors_presentN>",
         view=arv.LegacyThankyouView.as_view(), name="legacy_thankyou"),
    path("uncookie",
         view=arv.UncookieView.as_view(), name="uncookie"),
    path('favicon.ico', RedirectView.as_view(
        url=staticfiles_storage.url('images/favicon.ico')))
]

anwesende/users/urls.py
from django.urls import path

import anwesende.users.views as auv

app_name = "users"
urlpatterns = [
    path("~redirect/", view=auv.user_redirect_view, name="redirect"),
    path("~update/", view=auv.user_update_view, name="update"),
    path("<str:username>/", view=auv.user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path(
        "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("anwesende.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("anwesende.room.urls", namespace="room")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

anwesende/users/models.py
import django.contrib.auth.models as djcam
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(djcam.AbstractUser):
    """Default user for anwesende."""
    STAFF_GROUP = "datenverwalter"
    #: First and last name do not cover name patterns around the globe:
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def assign_datenverwalter_group(self) -> None:
        group = self.get_datenverwalter_group()
        self.groups.add(group)

    def is_datenverwalter(self) -> bool:
        return self.groups.filter(id=self.get_datenverwalter_group().id).exists()

    @classmethod
    def get_datenverwalter_group(cls) -> djcam.Group:
        if not djcam.Group.objects.filter(name=cls.STAFF_GROUP).exists():
            fresh_group = djcam.Group.objects.create(name=cls.STAFF_GROUP)  # noqa
        return djcam.Group.objects.get_by_natural_key(cls.STAFF_GROUP)

anwesende/users/forms.py
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(admin_forms.UserCreationForm):

    error_message = admin_forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

anwesende/room/views.py
import datetime as dt
import json
import logging
import os
import traceback
import typing as tg

import django.contrib.auth.mixins as djcam
import django.contrib.auth.views as djcav
import django.contrib.messages as djcm
import django.db.models as djdm
from django.db.models import Count
import django.http as djh
import django.urls as dju
import django.utils.timezone as djut
import django.views.generic.base as djvgb
import vanilla as vv  # Django vanilla views
from django.conf import settings

import anwesende.room.excel as are
import anwesende.room.forms as arf
import anwesende.room.models as arm
import anwesende.room.reports as arr
import anwesende.room.utils as aru
import anwesende.utils.date as aud
import anwesende.utils.lookup  # noqa,  registers lookup
import anwesende.utils.qrcode as auq

COOKIENAME = 'anwesende'


class AddIsDatenverwalter:
    """
    Sets user and is_datenverwalter flag in self and in context.
    """
    def dispatch(self, request: djh.HttpRequest, *args, **kwargs) -> djh.HttpResponse:
        self.user = self.request.user  # type: ignore
        self.is_datenverwalter = self.user.is_authenticated \
            and self.user.is_datenverwalter()
        return super().dispatch(request, *args, **kwargs)  # type: ignore

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # type: ignore
        context['user'] = self.user
        context['is_datenverwalter'] = self.is_datenverwalter
        return context


class AddSettings:
    """Put 'settings' in context: base.html requires it."""
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)  # type: ignore
        context['settings'] = settings
        return context


class FAQView(AddSettings, vv.TemplateView):
    template_name = "room/faq.html"


class HomeView(AddSettings, vv.TemplateView):
    template_name = "room/home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['dummyseat'] = arm.Seat.get_dummy_seat()
        return context


class ImportView(AddIsDatenverwalter, AddSettings, vv.FormView):
    """Import-Excel-for-QR-code-creation dialog."""
    form_class = arf.UploadFileForm
    template_name = "room/import.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.is_datenverwalter:
            interval = dt.timedelta(days=8)
            imports = arm.Importstep.displayable_importsteps(interval)
        else:
            room = arm.Seat.get_dummy_seat().room
            importstep = room.importstep
            importstep.organization = room.organization  # type: ignore[attr-defined]
            importstep.department = room.department  # type: ignore[attr-defined]
            imports = [importstep] 
        context['imports'] = imports
        context['settings'] = settings
        return context

    def form_invalid(self, form: arf.UploadFileForm):
        logging.getLogger('error').error(f"ImportView invalid: {form.errors}")
        return super().form_invalid(form)

    def form_valid(self, form: arf.UploadFileForm):
        filename = form.cleaned_data['excelfile']  # form has created the file
        self.importstep = are.create_seats_from_excel(filename, self.user)
        os.remove(filename)
        logging.info(f"ImportView({self.importstep})")
        return super().form_valid(form)

    def get_success_url(self):
        return dju.reverse('room:qrcodes-byimport', kwargs=dict(pk=self.importstep.pk))

    def post(self, request, *args, **kwargs):
        if not self.is_datenverwalter:
            next = self.request.get_full_path()
            login_url = dju.reverse('account_login')
            return djcav.redirect_to_login(next, login_url, 'next')
        return super().post(request, *args, **kwargs)

class QRcodesByImportView(AddIsDatenverwalter, AddSettings, vv.DetailView):
    """Show printable QR codes created in one Importstep."""
    model = arm.Importstep
    template_name = "room/qrcodes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        seats = arm.Seat.objects.filter(room__importstep=self.object)
        context['seats'] = seats
        context['listtype'] = 'importstep'
        return context

    def get_object(self):
        object = super().get_object()
        if self.is_datenverwalter or object == arm.Seat.get_dummy_seat().room.importstep:
            return object
        else:
            raise djh.Http404


class QRcodesByRoomsView(djcam.LoginRequiredMixin, 
                         AddIsDatenverwalter, AddSettings, vv.TemplateView):
    """Show printable QR codes for one room or one building."""
    template_name = "room/qrcodes.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['seats'] = self.get_queryset().all()
        context['listtype'] = 'byrooms'
        return context

    def get(self, request, *args, **kwargs):
        pop_org_dept_bldg_room(self)
        return super().get(request, *args, **kwargs)
        
    def get_queryset(self):
        qs = arm.Seat.objects.filter(
                room__organization=self.organization,
                room__department=self.department,
                room__building=self.building)
        if self.room:
            return qs.filter(room__room=self.room)
        else:
            return qs

def pop_org_dept_bldg_room(view):
    """
    Get certain URL params (if present) which come in slash-escaped in original form.
    See aru.escape_slash for rationale.
    """
    for arg in ('organization', 'department', 'building', 'room'):
        val = view.kwargs.pop(arg, "")
        setattr(view, f"{arg}", aru.unescape_slash(val))  # the real value


class QRcodeView(AddIsDatenverwalter, AddSettings, vv.View):
    """Render one QR code as SVG."""
    def get(self, request, *args, **kwargs):
        if not self.is_datenverwalter \
                and kwargs['hash'] != arm.Seat.get_dummy_seat().hash:
            raise djh.Http404
        path = dju.reverse('room:visit', kwargs=dict(hash=kwargs['hash']))
        url = settings.SHORTURL_PREFIX + path
        qrcode_bytes = auq.qrcode_data(url, imgtype='svg')
        return djh.HttpResponse(qrcode_bytes, content_type="image/svg+xml")


class ShowRoomsView(djcam.LoginRequiredMixin,
                    AddIsDatenverwalter, AddSettings, vv.TemplateView):
    """Browse list of departments, buildings, rooms; navigate to QR codes."""
    template_name = "room/show_rooms.html"

    def get(self, request, *args, **kwargs):
        pop_org_dept_bldg_room(self)
        return super().get(request, *args, **kwargs)

    def get_context_data(self):
        context = super().get_context_data()
        if self.building:
            context['type'] = "building"
            context['rooms'] = arm.Room.objects.filter(
                    organization=self.organization,
                    department=self.department,
                    building=self.building)
        elif self.department:
            context['type'] = "department"
            context['buildings'] = (arm.Room.objects
                    .filter(organization=self.organization, 
                            department=self.department)
                    .order_by('building')
                    .values('building')
                    .annotate(rooms=Count("id", distinct=True)))
        else:
            context['type'] = "overview"
            context['departments'] = (arm.Room.objects
                    .order_by('organization', 'department')
                    .values('organization', 'department')
                    .annotate(buildings=Count("building", distinct=True)))
        return context


class VisitView(AddSettings, vv.CreateView):
    """Centerpiece: The registration dialog for room visitors."""
    model = arm.Visit
    form_class = arf.VisitForm
    template_name = "room/visit.html"

    def get_success_url(self):
        return dju.reverse('room:thankyou', 
                           kwargs=dict(hash=self.object.seat.hash))
    
    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        hashvalue = self.kwargs['hash']
        if not arm.Seat.exists(hashvalue):
            raise djh.Http404()
        seat = arm.Seat.by_hash(hashvalue)
        ctx['seat'] = seat
        ctx['room'] = seat.room
        ctx['settings'] = settings
        retention_3g = settings.DATA_RETENTION_DAYS_STATUS_3G
        if settings.USE_STATUS_3G_FIELD and \
           retention_3g <= settings.DATA_RETENTION_DAYS:
            ctx['status_3g_stmt_de'] = ("Der 3G-Status wird bereits nach %d Tagen gelöscht." %
                                       retention_3g)
            ctx['status_3g_stmt_en'] = ("The vaccination status will be deleted after %d days." %
                                       retention_3g)
        else:
            ctx['status_3g_stmt_de'] = ctx['status_3g_stmt_en'] = ""
        return ctx

    
    def get_form(self, data=None, files=None, **kwargs):
        if data:  # POST
            data = {k: v for k, v in data.items()}  # extract ordinary dict
            return arf.VisitForm(data=data, files=files, **kwargs)
        # else GET:
        if COOKIENAME in self.request.COOKIES:
            try:
                thecookie = self.request.COOKIES[COOKIENAME]
                initial = json.loads(thecookie)
            except json.JSONDecodeError as err:
                tb = traceback.format_exc(limit=12, chain=True)
                logging.warning(f"VisitView: broken cookie >>>>{thecookie}<<<<\n{tb}")
                initial = dict(cookie=arm.Visit.make_cookie())
                logging.info(f"VisitView: ersatz {initial}")
        else:
            initial = dict(cookie=arm.Visit.make_cookie())
            logging.info(f"VisitView: new {initial}")

anwesende/users/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

anwesende/templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}a.nwesen.de{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Simple attendance registration for universities having pandemics (CoViD19_vhrpskumfc)">
    <meta name="author" content="Lutz Prechelt">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicon-32x32.png' %}">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'room:home' %}">a.nwesen.de</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'room:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'room:faq' %}">FAQs</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">Profil</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">Abmelden</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">Datenverwaltung</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Quiet here, isn't it?</p>
      {% endblock content %}

      {% block footer %}
        <small>
          <a href="{{ settings.GDPR_PROCESSOR_URL }}">Impressum</a>
          &bullet;
          <a href="mailto:{{ settings.TECH_CONTACT }}">Serverbetrieb</a>
          &bullet;
          {{ settings.PRIVACYINFO_DE|safe }}
          &bullet;
          <a href="https://github.com/prechelt/anwesende/">Open Source</a>
        </small>
      {% endblock footer %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}
    

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      
      <script src="{% static 'js/project.js' %}"></script>
      

    {% endblock javascript %}
  </body>
</html>
 